rust-vsock/tokio-vsock

- src/mio/listener.rs
I noticed this couldn't accept in a non-blocking fashion. It sets the each non-listening streams to non-blocking, but not the listener.
> Set the mio vsock listener to non-blocking

- Cargo.toml
- src/lib.rs
- src/listener.rs
- src/mio/listener.rs
- src/mio/stream.rs
- src/stream.rs
- test_server/Cargo.lock
- test_server/Cargo.toml
- test_server/src/main.rs
- tests/vsock.rs
- Bump `vsock-rs` from 0.2.2 to 0.2.3
- Remove dependence on nix and re-export SockAddr, VsockAddr
- Add methods connect_with_cid_port and bind_with_cid_port
- Bump version to 0.2.3
> Upgrade vsock-rs and remove dependence on nix

- Cargo.toml
Bump vsock from 0.2.3 to 0.2.4 to fix fd leak problem 
Release v0.3.1
Fixes: rust-vsock/vsock-rs#15
Signed-off-by: Tim Zhang <tim@hyper.sh>
> release: v0.3.1 and bump vsock from 0.2.3 to 0.2.4

- src/listener.rs
- src/stream.rs
This is a second attempt at handling interrupts in tokio-vsock. (First attempt: #8)
Now, after some spelunking, it appears the cause of interrupts is `firecracker` itself.
I've been seeing [`raising IRQ`](https://github.com/firecracker-microvm/firecracker/blob/9720e6f917474bd97973bc4e33bf5d83fe8d59a1/src/devices/src/virtio/vsock/device.rs#L123) logs from firecracker concerning the guest vsock.
I don't exactly know what purpose this serves, but the end result is that we need to handle interrupts in a graceful manner.
Therefore I'm hoping this simple PR can get approved and merge or else we're forced to keep using my fork. This is also fine, but given then rising popularity of Firecracker, I expect more people will stumble on this issue.
> Handle interrupts

- .gitignore
.vscode directory stores the workspace settings of the "Visual Studio Code" editor.
We should ignore it for everybody has her/his own editor settings.
> gitignore: ignore .vscode directory

- Cargo.toml
- src/lib.rs
- src/stream.rs
Implement the `tonic::transport::server::Connected` trait onto
`VsockStream` such that it may be used to build a tonic server.
>  Implement Connected trait from tonic

- src/stream.rs
- tests/vsock.rs
If connect() syscall does not immediately connect, use getsockopt(SOL_SOCKET, SO_ERROR) to check if it succeeded when the socket does become writable.
> Check if async connect succeeds or fails

- Cargo.toml
- src/lib.rs
- src/listener.rs
- src/stream.rs
- src/tonic_support.rs
Update vsock from 0.2.4 to 0.3.0. Changes are made according to https://github.com/rust-vsock/vsock-rs/commit/db589aa30ce36826198aa63df8e81d7a175f5266.
> Bump dependency versions

- src/stream.rs
The len argument of connect isn't guaranteed to always be u32
(for example, some android platforms use i32).
Fixes rust-vsock/tokio-vsock#28
> Cast size_of::<sockaddr_vm>() to socklen_t

- Cargo.toml
Bump the major version for API has changed in #25.
> release: v0.4.0

- src/lib.rs
These constants are useful when constructing new `VsockAddr`s and are currently not reexported thus making the consuming library/application require to either write the values themselves (very brittle), or add an unnecessary dependency on either nix or vsock.
tokio-vsock already depends on vsock-rs, thus we can just reexport these values.
> feat: Expose vsock::VM_ADDR_* constants

- src/lib.rs
- src/split.rs
- src/stream.rs
- tests/vsock.rs
VsockStream has been reworked to have a Owned (the previous API) and a Borrowed (the new API) variant. This comes with the following **Breaking Changes**:
- `VsockStream::split(self)` has been renamed `VsockStream::into_split`
- `VsockStream::split(&mut self)` has been added
- `split::{ReadHalf, WriteHalf}` have been renamed to `split::{OwnedReadHalf, OwnedWriteHalf}`
- New structs have been added:
- `split::ReadHalf<'a>` a borrowed ReadHalf of a VsockStream
- `split::WriteHalf<'a>` a borrowed WriteHalf of a VsockStream
The borrowed variants have the benefit of beeing chaper to construct/use as they rely on the fact that a `&mut` must be unique, thus when they are dropped the VsockStream ca be safely used again.
It also helps making it consistant with the tokio sockets and introduces no …
> feat!: Mirror tokio Stream Api with split and into_split

- Cargo.toml
- src/split.rs
This removes Atomics in favor of tokio's Mutex. It should be a safer alternative (and less likely to cause UB).
> feat(split): Rely on tokio's sync primitives

- .github/dependabot.yml
- .github/workflows/commit-message-check.yaml
This should help us keep on top of dependency version updates.
> Enable dependabot.

- src/listener.rs
- src/stream.rs
It's already implemented for the underlying `vsock::{VsockStream, VsockListener}`.
> impl AsFd for VsockStream & VsockListener

- Cargo.toml
Bump the major version for API changes in #30 and #40.
Fixes #42.
> release: v0.5.0

- README.md
Given `tokio-vsock` has been used in production for a number of years now, it's definitely no longer alpha quality (which was a comment I added to the README, when I initially released the project as a PoC).
Addresses: #44
> docs: definitely no longer alpha quality

- Cargo.toml
- src/lib.rs
- src/stream.rs
- tests/vsock.rs
I added macOS support for vsock-rs by PR https://github.com/rust-vsock/vsock-rs/pull/44. This PR adds macOS support for tokio-vsock.
This change is needed to use this crate in the macOS guest of Virtualization.framework.
One issue of this change is that it needs the latest vsock-rs. It can be resolved by releasing a new version of vsock-rs.
> build: Add support for macOS

- Cargo.toml
Bump the major version for API changes in #47.
As requested in #51.
> Prepare for 0.6.0 release

- src/listener.rs
- tests/vsock.rs
I encountered trouble when implementing the [`Listener`](https://github.com/rwf2/Rocket/blob/master/core/lib/src/listener/listener.rs#L14) from rocket for `VsockListener`, because it uses `&self`.
```rust
impl rocket::listener::Listener for VsockListener {
type Accept = (vsock::VsockStream, vsock::VsockAddr);
type Connection = VsockConnection;
async fn accept(&self) -> io::Result<Self::Accept> {
let (stream, addr) = self.listener.accept().await?;
Ok((stream, addr))
}
...
}
```
The [TcpListener](https://docs.rs/tokio/latest/src/tokio/net/tcp/listener.rs.html#160-169) from tokio is also using `&self`.
So, I think it should also use `&self` here.
> Use `&self` instead of `&mut self` for poll_accept

- Cargo.toml
- src/lib.rs
- src/tonic_support.rs
The current way that `tokio-vsock` tries to support multiple `tonic` versions is problematic, and is a regression from 0.6.0 (which used `version = "0.12.0"` for the tonic dependency).
https://github.com/rust-vsock/tokio-vsock/blob/d52af1bb62ce02908a7776433bdc1cdbcdbfcc1a/Cargo.toml#L22
This does not mean "tokio-vsock supports every tonic version from 0.5 through 0.12". It means "tokio-vsock supports a **single random** version of tonic between 0.5 and 0.12 according to Cargo's whim". Cargo does not expose any public way to control what choice of tonic would be used by this dependency.
One possible way the problems would manifest (there are many) is:
- Somebody writes a Cargo.toml depending on `tokio-vsock = { version = "0.6", features = ["tonic"] }` and `tonic = "0.11"`. In this …
> Expose choice of supported tonic version

- .github/workflows/bvt.yaml
- Cargo.toml
- Makefile
Add a nightly toolchain to test builds using the `-Z direct-minimum-dependencies` flag. This ensures our minimum version requirements are compatible with our source code.
This required bumping some versions:
- libc: `0.2.138` -> `0.2.158` as `vsock-rs` depends on `0.2.158`.
- tokio: `1` -> ~~`1.27` as we depend on methods/trait impls which are only available starting that version.~~ `1.34` as tonic 0.12 requires tokio 1.34
This ensures our minimum `tonic` requirement still compiles.
This should be released as `0.6.1` as requested by @cryo28 on #53
> feat: add nightly minimum dependencies test

- Cargo.toml
Bump the major version for #54 which changed API and #56 which removed features.
Also this release includes #53 and #55.
> release: v0.7.0

- .github/workflows/commit-message-check.yaml
The original limit 72 was too strict to follow.
> gh: Increase the maximum word limit for commit message body

- Cargo.toml
- src/axum_support.rs
- src/lib.rs
Everything about this PR is mostly obvious, with the feature being named `axum08` similarly to the `tonic`-related compat features. There is one exception, however, that being the accept error handling behavior: the `Listener`'s `accept` definition is **infallible** and states:
```rust
/// If the underlying accept call can return an error, this function must
/// take care of logging and retrying.
```
I used the approach `axum` developers themselves used for implementing `Listener` for TCP and UDS listeners, more info in the `handle_accept_error` method that is almost a direct copy-paste from `axum`'s internals. My assumption is that if it's considered "good enough" by `axum`, it should be for `tokio-vsock`, but I might be wrong.
> Implement optional support for axum 0.8's Listener trait
